# Generated by Django 3.2.7 on 2021-09-14 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='is_mvp',
            new_name='hire_date',
        ),
    ]
